/**
 * Display labels for London postal-area outcodes — the colloquial
 * neighbourhood name people recognise ("NW3 → Hampstead", "N9 →
 * Edmonton"). Used purely to annotate the covering-outcode chips in the
 * search form so it's obvious what each outcode is when toggling areas
 * on/off; it never affects what gets scraped.
 *
 * Curated from the per-area Wikipedia "X postcode area" coverage tables
 * (E/EC/N/NW/SE/SW/W/WC). Covers the eight London postal areas including
 * the geographic letter-suffixed central districts; non-geographic codes
 * (N1P, N81, EC1P, …) are deliberately absent. Outcodes outside London's
 * postal areas (IG, BR, CR, EN, … that a near-border search can pull in)
 * have no entry and fall back to the bare outcode.
 */
export const OUTCODE_AREAS: Record<string, string> = {
  // E
  E1: "Whitechapel",
  E1W: "Wapping",
  E2: "Bethnal Green",
  E3: "Bow",
  E4: "Chingford",
  E5: "Clapton",
  E6: "East Ham",
  E7: "Forest Gate",
  E8: "Hackney",
  E9: "Homerton",
  E10: "Leyton",
  E11: "Leytonstone",
  E12: "Manor Park",
  E13: "Plaistow",
  E14: "Canary Wharf",
  E15: "Stratford",
  E16: "Canning Town",
  E17: "Walthamstow",
  E18: "South Woodford",
  E20: "Olympic Park",
  E22: "Isle of Dogs",

  // EC
  EC1A: "St Bartholomew's",
  EC1M: "Clerkenwell",
  EC1N: "Hatton Garden",
  EC1R: "Finsbury",
  EC1V: "Finsbury",
  EC1Y: "St Luke's",
  EC2A: "Shoreditch",
  EC2M: "Liverpool Street",
  EC2N: "Old Broad Street",
  EC2R: "Bank",
  EC2V: "Guildhall",
  EC2Y: "Barbican",
  EC3A: "Aldgate",
  EC3M: "Fenchurch Street",
  EC3N: "Tower Hill",
  EC3R: "Monument",
  EC3V: "Cornhill",
  EC4A: "Fetter Lane",
  EC4M: "St Paul's",
  EC4N: "Mansion House",
  EC4R: "Cannon Street",
  EC4V: "Blackfriars",
  EC4Y: "Temple",

  // N
  N1: "Islington",
  N1C: "King's Cross",
  N2: "East Finchley",
  N3: "Finchley",
  N4: "Finsbury Park",
  N5: "Highbury",
  N6: "Highgate",
  N7: "Holloway",
  N8: "Hornsey",
  N9: "Edmonton",
  N10: "Muswell Hill",
  N11: "New Southgate",
  N12: "North Finchley",
  N13: "Palmers Green",
  N14: "Southgate",
  N15: "South Tottenham",
  N16: "Stoke Newington",
  N17: "Tottenham",
  N18: "Upper Edmonton",
  N19: "Archway",
  N20: "Whetstone",
  N21: "Winchmore Hill",
  N22: "Wood Green",

  // NW
  NW1: "Camden Town",
  NW2: "Cricklewood",
  NW3: "Hampstead",
  NW4: "Hendon",
  NW5: "Kentish Town",
  NW6: "Kilburn",
  NW7: "Mill Hill",
  NW8: "St John's Wood",
  NW9: "Kingsbury",
  NW10: "Willesden",
  NW11: "Golders Green",

  // SE
  SE1: "Southwark",
  SE2: "Abbey Wood",
  SE3: "Blackheath",
  SE4: "Brockley",
  SE5: "Camberwell",
  SE6: "Catford",
  SE7: "Charlton",
  SE8: "Deptford",
  SE9: "Eltham",
  SE10: "Greenwich",
  SE11: "Kennington",
  SE12: "Lee",
  SE13: "Lewisham",
  SE14: "New Cross",
  SE15: "Peckham",
  SE16: "Rotherhithe",
  SE17: "Walworth",
  SE18: "Woolwich",
  SE19: "Crystal Palace",
  SE20: "Penge",
  SE21: "Dulwich",
  SE22: "East Dulwich",
  SE23: "Forest Hill",
  SE24: "Herne Hill",
  SE25: "South Norwood",
  SE26: "Sydenham",
  SE27: "West Norwood",
  SE28: "Thamesmead",

  // SW
  SW1A: "Westminster",
  SW1E: "Victoria",
  SW1H: "St James's Park",
  SW1P: "Pimlico/Westminster",
  SW1V: "Pimlico",
  SW1W: "Belgravia",
  SW1X: "Knightsbridge",
  SW1Y: "St James's",
  SW2: "Brixton Hill",
  SW3: "Chelsea",
  SW4: "Clapham",
  SW5: "Earls Court",
  SW6: "Fulham",
  SW7: "South Kensington",
  SW8: "South Lambeth",
  SW9: "Brixton",
  SW10: "West Brompton",
  SW11: "Battersea",
  SW12: "Balham",
  SW13: "Barnes",
  SW14: "Mortlake",
  SW15: "Putney",
  SW16: "Streatham",
  SW17: "Tooting",
  SW18: "Wandsworth",
  SW19: "Wimbledon",
  SW20: "Raynes Park",

  // W
  W1B: "Regent Street",
  W1C: "Oxford Street",
  W1D: "Soho",
  W1F: "Soho",
  W1G: "Harley Street",
  W1H: "Marylebone",
  W1J: "Mayfair",
  W1K: "Mayfair",
  W1S: "Mayfair",
  W1T: "Fitzrovia",
  W1U: "Marylebone",
  W1W: "Fitzrovia",
  W2: "Paddington",
  W3: "Acton",
  W4: "Chiswick",
  W5: "Ealing",
  W6: "Hammersmith",
  W7: "Hanwell",
  W8: "Kensington",
  W9: "Maida Vale",
  W10: "North Kensington",
  W11: "Notting Hill",
  W12: "Shepherd's Bush",
  W13: "West Ealing",
  W14: "West Kensington",

  // WC
  WC1A: "New Oxford Street",
  WC1B: "Bloomsbury",
  WC1E: "Bloomsbury",
  WC1H: "St Pancras",
  WC1N: "Russell Square",
  WC1R: "Gray's Inn",
  WC1V: "Holborn",
  WC1X: "King's Cross",
  WC2A: "Lincoln's Inn",
  WC2B: "Aldwych",
  WC2E: "Covent Garden",
  WC2H: "Leicester Square",
  WC2N: "Charing Cross",
  WC2R: "Temple",
};

/**
 * Colloquial area name for an outcode (e.g. "NW3" → "Hampstead"), or
 * `null` if we don't have one (non-London outcodes, fringe districts).
 * Case- and whitespace-insensitive.
 */
export function outcodeAreaName(outcode: string): string | null {
  return OUTCODE_AREAS[outcode.trim().toUpperCase()] ?? null;
}
