/**
 * EPC API client public surface.
 *
 * Re-exports the typed SDK and types generated by openapi-ts plus the
 * hand-written `createEpcClient` factory.
 */

export { createEpcClient } from "./client";
export * from "./generated";
