export default {
  // Your t-stack org slug (used as the local Doppler scope under
  // ~/.t-stack/orgs/<org> and the Pulumi org). Change to your own.
  org: "yourorg",
  archetype: "single-cloudflare",
  projectName: "gaff",
  // The public hostname the deployed Worker is served on. Change to your own.
  domain: "gaff.example.com",
  structure: "single",
  cloudProvider: "cloudflare",
  iac: "pulumi",
  runtime: "workers",
  frontend: "tanstack-start",
  backend: "none",
  docs: "none",
  api: "none",
  database: "postgres",
  databaseHost: "neon",
  databaseRegion: "aws-eu-central-1",
  orm: "drizzle",
  auth: "better-auth",
  storage: "r2",
  payments: "none",
  packageManager: "bun",
  git: true,
  envs: "prd",
  trigger: true,
  access: true,
  hookdeck: false,
} as const;
