export default {
  org: "timothygithinji",
  archetype: "single-cloudflare",
  projectName: "gaff",
  domain: "gaff.example.com",
  structure: "single",
  cloudProvider: "cloudflare",
  iac: "pulumi",
  runtime: "workers",
  frontend: "tanstack-start",
  backend: "none",
  docs: "none",
  api: "none",
  database: "postgres",
  databaseHost: "neon",
  databaseRegion: "aws-eu-central-1",
  orm: "drizzle",
  auth: "better-auth",
  storage: "r2",
  payments: "none",
  packageManager: "bun",
  git: true,
  envs: "prd",
  trigger: true,
  access: true,
  hookdeck: false,
} as const;
