/**
 * postcodes.io API client public surface.
 *
 * Re-exports the typed SDK and types generated by openapi-ts plus the
 * hand-written `createPostcodesClient` factory.
 */

export { createPostcodesClient } from "./client";
export type { CreatePostcodesClientOptions } from "./client";
export * from "./generated";
