#!/usr/bin/env bun
/**
 * Generate Better Auth's required Drizzle schema, then rewrite it to live
 * inside a dedicated `better_auth` Postgres schema (instead of `public`).
 *
 * Pipeline:
 *   1. Run `@better-auth/cli generate` against `src/lib/auth.config.ts`
 *      into a temp file. The CLI emits standard `pgTable(...)` calls.
 *   2. Post-process: prepend `pgSchema("better_auth")` and rewrite every
 *      `pgTable(` call to `betterAuth.table(`. Add a leading header
 *      banner so it's obvious the file is generated.
 *   3. Write the result to `db/auth-schema.ts`.
 *
 * This wrapper exists because @better-auth/cli has no way to target a
 * non-public Postgres schema — and we want the cli to remain the source
 * of truth for *which* tables exist (so adding plugins like organization
 * or passkey just means updating src/lib/auth.config.ts and re-running).
 *
 * Usage:
 *   bun run auth:generate
 */

import { execFileSync, spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const CONFIG_PATH = "src/lib/auth.config.ts";
const TARGET_PATH = "db/auth-schema.ts";
const SCHEMA_NAME = "better_auth";

const HEADER = `// This file is generated by \`bun run auth:generate\`.
// Source of truth: src/lib/auth.config.ts (the auth config the Better Auth
// CLI introspects) — re-running the script regenerates this file. The
// post-processor moves the tables into a dedicated \`${SCHEMA_NAME}\`
// Postgres schema by rewriting \`pgTable(...)\` to \`betterAuth.table(...)\`.
//
// To pick up new Better Auth plugins / table changes:
//   1. Update src/lib/auth.config.ts (and src/lib/auth.ts).
//   2. \`bun run auth:generate\`
//   3. \`bun run db:generate\` to land a migration for the schema diff.
`;

const log = {
  info: (msg: string) => console.log(`\x1b[34m[auth:generate]\x1b[0m ${msg}`),
  success: (msg: string) =>
    console.log(`\x1b[32m[auth:generate]\x1b[0m ✓ ${msg}`),
  error: (msg: string) =>
    console.error(`\x1b[31m[auth:generate]\x1b[0m ✗ ${msg}`),
};

function runCli(outputPath: string): void {
  if (!existsSync(CONFIG_PATH)) {
    throw new Error(
      `auth config not found at ${CONFIG_PATH} — see top-of-file doc.`
    );
  }
  log.info(`Running @better-auth/cli generate → ${outputPath}`);
  const result = spawnSync(
    "bunx",
    [
      "--bun",
      "@better-auth/cli",
      "generate",
      "--config",
      CONFIG_PATH,
      "--output",
      outputPath,
      "--y",
    ],
    { stdio: "inherit" }
  );
  if (result.status !== 0) {
    throw new Error(
      `@better-auth/cli generate exited with status ${result.status}`
    );
  }
  if (!existsSync(outputPath)) {
    throw new Error(
      `@better-auth/cli claimed success but ${outputPath} doesn't exist.`
    );
  }
}

const PG_TABLE_CALL_RE = /\bpgTable\(/g;
const PG_CORE_IMPORT_RE =
  /^import\s*\{\s*([^}]*?)\s*\}\s*from\s*["']drizzle-orm\/pg-core["'];?$/m;
const RELATIONS_IMPORT_RE =
  /^import\s*\{\s*relations\s*\}\s*from\s*["']drizzle-orm["'];?\s*\n?/gm;
// Matches everything from the first top-level `*Relations` export through
// end of file. The CLI always emits relations after all tables, so this
// chops the trailing block off cleanly. We re-declare relations in
// db/schema.ts where they can span both auth + domain tables.
const RELATIONS_TAIL_RE =
  /\n?export\s+const\s+\w+Relations\s*=\s*relations\([\s\S]*$/;

function rewriteToSchema(raw: string): string {
  if (!PG_TABLE_CALL_RE.test(raw)) {
    throw new Error(
      "Generated file has no pgTable() calls — refusing to write " +
        "an empty schema. Has the Better Auth CLI changed its output format?"
    );
  }
  // Reset lastIndex after the .test() above so .replace() works from the start.
  PG_TABLE_CALL_RE.lastIndex = 0;

  const importMatch = raw.match(PG_CORE_IMPORT_RE);
  if (!importMatch) {
    throw new Error(
      "Generated file has no `drizzle-orm/pg-core` import — refusing " +
        "to rewrite. Has the Better Auth CLI changed its output format?"
    );
  }

  // Strip `pgTable` from the named imports (we no longer call it directly),
  // and ensure `pgSchema` is imported.
  const named = importMatch[1] ?? "";
  const filtered = named
    .split(",")
    .map((s) => s.trim())
    .filter((s) => s.length > 0 && s !== "pgTable");
  if (!filtered.includes("pgSchema")) {
    filtered.unshift("pgSchema");
  }
  const newImport = `import { ${filtered.join(", ")} } from "drizzle-orm/pg-core";`;

  const schemaDecl = `\nexport const betterAuth = pgSchema("${SCHEMA_NAME}");\n`;

  let rewritten = raw.replace(PG_CORE_IMPORT_RE, `${newImport}${schemaDecl}`);
  rewritten = rewritten.replace(PG_TABLE_CALL_RE, "betterAuth.table(");
  rewritten = rewritten.replace(RELATIONS_TAIL_RE, "");
  rewritten = rewritten.replace(RELATIONS_IMPORT_RE, "");
  // Collapse the gaps left by stripped imports / relations blocks.
  rewritten = rewritten.replace(/\n{3,}/g, "\n\n");

  // Strip the CLI's trailing newline duplication if any, then prepend
  // our header.
  return `${HEADER}\n${rewritten.trimEnd()}\n`;
}

function main(): void {
  const tmp = mkdtempSync(join(tmpdir(), "gaff-auth-"));
  const rawPath = join(tmp, "auth-raw.ts");

  runCli(rawPath);

  const raw = readFileSync(rawPath, "utf-8");
  const rewritten = rewriteToSchema(raw);

  writeFileSync(TARGET_PATH, rewritten);
  log.success(`Wrote ${TARGET_PATH} (${rewritten.split("\n").length} lines)`);

  // Format with biome so the output matches the rest of the codebase.
  spawnSync("bunx", ["biome", "format", "--write", TARGET_PATH], {
    stdio: "ignore",
  });

  // Sanity check — typecheck the new file so we fail loudly if the CLI's
  // output drifted in a way our regex didn't anticipate.
  try {
    execFileSync("bunx", ["tsc", "--noEmit", "--skipLibCheck", TARGET_PATH], {
      stdio: "pipe",
    });
    log.success("Typecheck clean");
  } catch (err) {
    log.error(
      `Typecheck of ${TARGET_PATH} failed: ${
        err instanceof Error ? err.message : String(err)
      }`
    );
    process.exit(1);
  }
}

try {
  main();
} catch (err) {
  log.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
}
