#!/usr/bin/env bun
/**
 * Block Write/Edit on Drizzle's generated migration files.
 *
 * Migrations live in `drizzle/` (path comes from `drizzle.config.ts` →
 * `out: "./drizzle"`). New SQL files are generated by `drizzle-kit generate`,
 * never hand-authored. The `meta/_journal.json` and `meta/*_snapshot.json`
 * files track the migration chain — editing them by hand desyncs the
 * snapshot graph and produces a fork that `scripts/validation/migrations.ts`
 * will then reject.
 *
 * Adapted from fanya-labs/playt's .claude/scripts/validate-drizzle-files.ts.
 */

type HookInput = {
  tool_name?: string;
  tool_input?: { file_path?: string };
};

const input = (await Bun.stdin.json()) as HookInput;

if (input.tool_name !== "Write" && input.tool_name !== "Edit") {
  process.exit(0);
}

const filePath: string = input.tool_input?.file_path ?? "";

const projectDir = process.env.CLAUDE_PROJECT_DIR ?? process.cwd();
const relativePath = filePath.startsWith(projectDir)
  ? filePath.slice(projectDir.length + 1)
  : filePath;

const MIGRATIONS_DIR = "drizzle/";

// Block creating new SQL migrations directly (Write tool).
if (
  input.tool_name === "Write" &&
  relativePath.startsWith(MIGRATIONS_DIR) &&
  relativePath.endsWith(".sql")
) {
  console.error(
    "🚫 BLOCKED: Cannot create files directly in the migrations folder."
  );
  console.error("");
  console.error("Migration files must be generated by the Drizzle CLI:");
  console.error("  bun run db:generate");
  console.error("");
  console.error(
    "If you need a blank custom migration, ask the user to run the CLI."
  );
  console.error(`File attempted: ${relativePath}`);
  process.exit(2);
}

// Block any edit to the meta dir — Drizzle owns it.
if (relativePath.startsWith(`${MIGRATIONS_DIR}meta/`)) {
  console.error(`🚫 BLOCKED: Cannot edit files in ${MIGRATIONS_DIR}meta/.`);
  console.error("");
  console.error(
    "The journal and snapshot files are managed by Drizzle CLI. Editing"
  );
  console.error(
    "them manually forks the snapshot chain — scripts/validation/migrations.ts"
  );
  console.error("will reject the result.");
  console.error(`File attempted: ${relativePath}`);
  process.exit(2);
}

process.exit(0);
