import { relations, sql } from "drizzle-orm";
import {
  boolean,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  pgView,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";
// Better Auth's tables live in their own `better_auth` Postgres schema —
// see db/auth-schema.ts. That file is generated by `bun run auth:generate`
// from src/lib/auth.config.ts; don't hand-edit it. Relations are declared
// below so they can span both auth + domain tables.
export {
  account,
  betterAuth,
  session,
  user,
  verification,
} from "./auth-schema";
import type { SearchLocation } from "../src/lib/search-location";
import { account, session, user } from "./auth-schema";
import type { verification } from "./auth-schema";

// -----------------------------------------------------------------------------
// Gaff domain enums
// -----------------------------------------------------------------------------

export const householdRoleEnum = pgEnum("household_role", ["owner", "member"]);

export const listingStatusEnum = pgEnum("listing_status", [
  "active",
  "let_agreed",
  "removed",
]);

export const swipeOutcomeEnum = pgEnum("swipe_outcome", [
  "keep",
  "skip",
  "shortlist",
]);

export const jobStatusEnum = pgEnum("job_status", [
  "running",
  "success",
  "failure",
]);

/**
 * Pipeline stages a household moves a mutually-shortlisted cluster
 * through. The default "shortlisted" stage is derived from
 * `v_mutual_matches` — only stages beyond that need an explicit row in
 * `shortlist_pipeline`. See `listPipeline` for the merge logic.
 */
export const pipelineStatusEnum = pgEnum("pipeline_status", [
  "shortlisted",
  "contacted",
  "viewing_booked",
  "offer_made",
  "archived",
]);

/**
 * Reasons a household archives a cluster from the pipeline. Free-form
 * enough that we don't burn a migration adding values; tight enough
 * that the UI can label the most common cases distinctly.
 */
export const pipelineArchivedReasonEnum = pgEnum("pipeline_archived_reason", [
  "accepted",
  "passed",
  "let_to_someone_else",
  "withdrawn",
  "other",
]);

// -----------------------------------------------------------------------------
// Gaff domain tables
// -----------------------------------------------------------------------------

export const households = pgTable("households", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  /**
   * Watermark for the daily new-listings digest: the cutoff the next
   * digest counts "new since". NULL until the first digest runs (the task
   * treats null as "the last 24h" so the first email isn't a backlog
   * dump), then advanced to the send time on every run. See
   * `src/trigger/daily-digest.ts`.
   */
  lastDigestAt: timestamp("last_digest_at"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .$onUpdate(() => new Date())
    .notNull(),
});

export const householdMembers = pgTable(
  "household_members",
  {
    id: text("id").primaryKey(),
    householdId: text("household_id")
      .notNull()
      .references(() => households.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade", onUpdate: "cascade" }),
    role: householdRoleEnum("role").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    uniqueIndex("household_members_household_user_uniq").on(
      t.householdId,
      t.userId
    ),
    index("household_members_user_id_idx").on(t.userId),
  ]
);

export const searches = pgTable(
  "searches",
  {
    id: text("id").primaryKey(),
    householdId: text("household_id")
      .notNull()
      .references(() => households.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    name: text("name").notNull(),
    portals: text("portals").array().notNull(),
    /**
     * Canonical "where" the user wants to search. Replaces the older
     * single-outcode column. Shape is {@link SearchLocation} (see
     * `src/lib/search-location.ts`) — Google place_id + centroid + bounds
     * + pre-resolved per-portal tokens (Rightmove locationIdentifier,
     * Zoopla q string, OpenRent term+radius). Resolution happens at
     * form-submit; scrape-portal reads the cached refs directly.
     */
    location: jsonb("location").$type<SearchLocation>().notNull(),
    minBedrooms: integer("min_bedrooms"),
    maxBedrooms: integer("max_bedrooms"),
    minBathrooms: integer("min_bathrooms"),
    maxBathrooms: integer("max_bathrooms"),
    minPrice: integer("min_price"),
    maxPrice: integer("max_price"),
    /**
     * User-picked search radius around `location`, in miles. The UI
     * slider exposes Rightmove's vocab — 0, 0.25, 0.5, 1, 3, 5, 10, 15,
     * 20, 30, 40 — where 0 means "this area only" (no buffer).
     *
     * Applied at scrape-portal URL-build time:
     *   - Rightmove: emitted as `radius=<n>` (decimal miles).
     *   - Zoopla: emitted as `radius=<n>` (decimal miles).
     *   - OpenRent: converted to km integer with a floor of 2 (OR's
     *     UI minimum). See `openrentSearchUrl` in `src/lib/portal-urls.ts`.
     */
    radiusMiles: numeric("radius_miles", { precision: 5, scale: 2 })
      .notNull()
      .default("0"),
    propertyTypes: text("property_types").array().notNull(),
    /**
     * Places to subtract from the include scope. Same SearchLocation
     * shape; portalRefs unused (excludes are filter-time, not URL-time).
     * Postcode-type excludes drop listings by postcode-prefix match;
     * non-postcode excludes drop listings whose lat/lng falls inside
     * `bounds`. See `filterByExcludeLocations` in scrape-portal.ts.
     */
    excludeLocations: jsonb("exclude_locations")
      .$type<SearchLocation[]>()
      .notNull()
      .default(sql`'[]'::jsonb`),
    /**
     * Furnishing preference. `null` means "no filter".
     * Stored as plain text (not an enum) to keep the migration trivial;
     * Zod enforces the closed set at write time.
     */
    furnished: text("furnished"),
    /**
     * Must-have amenities. Closed set is enforced in Zod
     * (`["garden", "parking", "pets"]`); the column is plain text[] so
     * adding a new value later is a no-migration change.
     */
    mustHaves: text("must_haves").array().notNull().default(sql`'{}'::text[]`),
    /**
     * Listing categories to hide. Closed set is enforced in Zod
     * (`["student", "retirement", "house_share"]`). Per-portal mapping
     * lives in `src/lib/portal-urls.ts`:
     *   - Rightmove: `dontShow=studentLet,retirement,houseShare` (comma list)
     *   - Zoopla: `include_*=false` per category
     *   - OpenRent: no URL support — `filterByExclusions` in
     *     `src/trigger/scrape-portal.ts` drops shares post-scrape and
     *     `listingPassesExclusions` in `src/server/functions/review.ts`
     *     is the read-time backstop. OR does host rooms-in-shared-flats
     *     ("Room in a Shared House — …" titles); it just doesn't expose
     *     a URL filter for them.
     */
    exclusions: text("exclusions").array().notNull().default(sql`'{}'::text[]`),
    commuteTargets: jsonb("commute_targets")
      .$type<
        Array<{
          label: string;
          lat: number;
          lng: number;
          maxMinutes: number;
          mode: string;
        }>
      >()
      .notNull(),
    transportTargets: jsonb("transport_targets")
      .$type<
        Array<{
          amenity: "tube_station" | "train_station" | "bus_stop" | "tram_stop";
          mode: "walk" | "cycle" | "transit" | "drive";
          maxMinutes: number;
        }>
      >()
      .notNull()
      .default(sql`'[]'::jsonb`),
    active: boolean("active").default(true).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (t) => [index("searches_household_id_idx").on(t.householdId)]
);

export const propertyClusters = pgTable(
  "property_clusters",
  {
    id: text("id").primaryKey(),
    // Flat/unit numbers MUST be preserved by callers — normalisation logic
    // lives in src/lib/cluster/normalise.ts.
    normalisedAddress: text("normalised_address").notNull(),
    postcode: text("postcode"),
    lat: numeric("lat", { precision: 9, scale: 6 }),
    lng: numeric("lng", { precision: 10, scale: 6 }),
    /**
     * GSS code of the council tax billing authority (e.g. "E07000223"),
     * resolved once per building from `postcode` via postcodes.io
     * (`codes.admin_district`). Joined against `council_tax_rates` at
     * read time to estimate the annual bill from the listing's band.
     * NULL until `enrich-council-tax` runs, or for non-England postcodes
     * (the rate table is England-only). See `src/lib/council-tax.ts`.
     */
    councilTaxAuthorityCode: text("council_tax_authority_code"),
    /** Human-readable billing-authority name, for display alongside the estimate. */
    councilTaxAuthorityName: text("council_tax_authority_name"),
    /**
     * User-supplied full address for this building, entered manually when
     * the portals only exposed a street ("Brownlow Road, N11"). The user
     * reads the listing photos against Google Maps to pin the exact door,
     * which lets `enrich-epc` resolve the precise certificate instead of a
     * postcode-level estimate. NULL = no override; the scraped address +
     * reverse-geocoded postcode are used. See `setClusterAddress`.
     */
    userAddress: text("user_address"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (t) => [
    uniqueIndex("property_clusters_normalised_address_uniq").on(
      t.normalisedAddress
    ),
  ]
);

/**
 * Council tax rates by billing authority, seeded once per tax year from
 * MHCLG's "Council Tax levels set by local authorities in England"
 * dataset (see `scripts/seed-council-tax.ts`).
 *
 * We store only the area-average **Band D** figure per authority; the
 * other bands (A–H) are fixed statutory ratios of Band D (Local
 * Government Finance Act 1992, s.5), derived at read time in
 * `src/lib/council-tax.ts`. England only — Wales (bands A–I) and
 * Scotland (revised E–H multipliers) use different ratios and aren't
 * covered here.
 *
 * "Only so many councils": ~317 billing authorities, so the whole table
 * is a few hundred rows refreshed annually. Keyed (authorityCode,
 * taxYear) so historic years coexist; read paths take the latest seeded
 * year for the authority.
 */
export const councilTaxRates = pgTable(
  "council_tax_rates",
  {
    /** GSS code of the billing authority, matches `codes.admin_district`. */
    authorityCode: text("authority_code").notNull(),
    /** Billing-authority name as published in the source dataset. */
    authorityName: text("authority_name").notNull(),
    /** UK council tax year the figure applies to, e.g. "2025-26". */
    taxYear: text("tax_year").notNull(),
    /**
     * Area-average Band D council tax in **pence** (integer to avoid
     * float drift; source figures carry pence, e.g. £2,280.39).
     */
    bandDPence: integer("band_d_pence").notNull(),
    /** Provenance — the dataset URL/file the figure was seeded from. */
    source: text("source"),
    fetchedAt: timestamp("fetched_at").defaultNow().notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.authorityCode, t.taxYear] }),
    index("council_tax_rates_tax_year_idx").on(t.taxYear),
  ]
);

export const listings = pgTable(
  "listings",
  {
    id: text("id").primaryKey(),
    portal: text("portal").notNull(),
    portalListingId: text("portal_listing_id").notNull(),
    clusterId: text("cluster_id").references(() => propertyClusters.id, {
      onDelete: "set null",
      onUpdate: "cascade",
    }),
    searchId: text("search_id")
      .notNull()
      .references(() => searches.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    url: text("url").notNull(),
    title: text("title").notNull(),
    addressRaw: text("address_raw").notNull(),
    postcode: text("postcode"),
    bedrooms: integer("bedrooms"),
    bathrooms: integer("bathrooms"),
    priceMonthly: integer("price_monthly"),
    propertyType: text("property_type"),
    lat: numeric("lat", { precision: 9, scale: 6 }),
    lng: numeric("lng", { precision: 10, scale: 6 }),
    firstSeenAt: timestamp("first_seen_at").defaultNow().notNull(),
    lastSeenAt: timestamp("last_seen_at").defaultNow().notNull(),
    availableFrom: timestamp("available_from"),
    status: listingStatusEnum("status").default("active").notNull(),
    /**
     * Floor area in square feet, when the portal exposes it. Rightmove's
     * `sizings` array and Zoopla's `floorArea` both feed this; OpenRent
     * doesn't publish it. Stored as int (no fractional sq-ft) — closer
     * to how listing sites round the value than a numeric.
     */
    sizeSqFt: integer("size_sq_ft"),
    /** Council tax band letter (typically A–H). */
    councilTaxBand: text("council_tax_band"),
    /**
     * Portal-reported "first listed" date. Useful as a freshness signal
     * that doesn't drift the way `first_seen_at` does when the row is
     * re-clustered or backfilled.
     */
    publishedAt: timestamp("published_at"),
    /**
     * Closed tenant-acceptance flag for pets. `null` = portal didn't
     * say; `true`/`false` = explicit. Only `pets` is promoted to a
     * column today because that's the filter users ask for most often;
     * the rest of `tenantPreferences` lives in raw_json.
     */
    petsAccepted: boolean("pets_accepted"),
    rawJson: jsonb("raw_json").notNull(),
  },
  (t) => [
    // A physical listing can surface in multiple searches (e.g. two
    // households scraping the same outcode). Each (search, portal listing)
    // is its own row; cross-portal/cross-search dedupe happens via clusterId.
    uniqueIndex("listings_search_portal_listing_id_uniq").on(
      t.searchId,
      t.portal,
      t.portalListingId
    ),
    index("listings_portal_listing_id_idx").on(t.portal, t.portalListingId),
    index("listings_cluster_id_idx").on(t.clusterId),
    index("listings_search_id_idx").on(t.searchId),
    index("listings_status_idx").on(t.status),
  ]
);

export const listingPhotos = pgTable(
  "listing_photos",
  {
    id: text("id").primaryKey(),
    listingId: text("listing_id")
      .notNull()
      .references(() => listings.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    url: text("url").notNull(),
    r2Key: text("r2_key"),
    position: integer("position").notNull(),
  },
  (t) => [index("listing_photos_listing_id_idx").on(t.listingId)]
);

export const aiRuns = pgTable("ai_runs", {
  id: text("id").primaryKey(),
  listingId: text("listing_id").references(() => listings.id, {
    onDelete: "set null",
    onUpdate: "cascade",
  }),
  promptVersion: text("prompt_version").notNull(),
  model: text("model").notNull(),
  startedAt: timestamp("started_at").defaultNow().notNull(),
  finishedAt: timestamp("finished_at"),
  status: jobStatusEnum("status").notNull(),
  inputTokens: integer("input_tokens"),
  outputTokens: integer("output_tokens"),
  costUsd: numeric("cost_usd"),
  errorMessage: text("error_message"),
});

export const enrichments = pgTable(
  "enrichments",
  {
    id: text("id").primaryKey(),
    listingId: text("listing_id")
      .notNull()
      .references(() => listings.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    promptVersion: text("prompt_version").notNull(),
    /**
     * AI-extracted features. v1 (`PROMPT_VERSION=v1.0.0`) stored boolean
     * amenity flags + a fake floorplan readout — those columns are
     * preserved on disk for already-enriched rows but new rows under
     * v2.0.0+ use the shape declared here: a one-line summary plus
     * highlights/watchouts arrays with `label` + `detail`. See
     * `src/lib/ai/prompt.ts` for the live source of truth.
     */
    features: jsonb("features")
      .$type<{
        summary?: string | null;
        highlights?: Array<{ label: string; detail: string | null }>;
        watchouts?: Array<{
          severity: "caution" | "problem";
          label: string;
          detail: string | null;
        }>;
        [key: string]: unknown;
      }>()
      .notNull(),
    epc: jsonb("epc"),
    commuteMinutes: jsonb("commute_minutes").$type<Record<string, number>>(),
    /**
     * Broadband availability from BT Wholesale.
     * - technology: best available, in order FTTP > FTTC > ADSL.
     * - downloadMbps / uploadMbps: estimated max speed for that tier.
     * - fttpAvailable: shortcut for the headline "fibre or not" check.
     */
    broadband: jsonb("broadband").$type<{
      technology: "FTTP" | "FTTC" | "ADSL" | null;
      downloadMbps: number | null;
      uploadMbps: number | null;
      fttpAvailable: boolean;
    }>(),
    /**
     * data.police.uk monthly crime aggregate, fetched once per cluster.
     * - month: e.g. "2026-03" (most recent month with data).
     * - total: count of all crimes within a 1mi radius for that month.
     * - byCategory: per-category counts (anti-social-behaviour, burglary, …).
     */
    crime: jsonb("crime").$type<{
      month: string;
      total: number;
      byCategory: Record<string, number>;
    }>(),
    /**
     * Environment Agency flood risk for the cluster's location.
     * Values mirror the EA's "Risk of Flooding from Rivers and Sea" bands.
     */
    flood: jsonb("flood").$type<{
      riskLevel: "very-low" | "low" | "medium" | "high" | "unknown";
    }>(),
    /**
     * Counts of OpenStreetMap amenities within `withinMeters` of the
     * cluster. Categories are fixed at write-time so the UI can render
     * a stable grid; consult `src/lib/amenities.ts` for the live list.
     */
    amenities: jsonb("amenities").$type<{
      withinMeters: number;
      counts: Record<string, number>;
    }>(),
    /**
     * Per-station travel times from the cluster to its nearest stations,
     * computed via Google Routes v2 in `enrich-station-routes.ts`.
     *
     *   - `walkMinutes`: realistic walking time via actual paths
     *     (Google's WALK mode), not the linear `distanceMiles × 20`
     *     heuristic the review card uses.
     *   - `transitMinutes`: time by public transit (bus / tube / rail
     *     combined) for an 09:00 London-weekday arrival, same as
     *     `commuteMinutes`.
     *
     * Each entry's `name` matches a `rawJson.nearestStations[].name`.
     * Sourced from Rightmove parsed data only — Zoopla / OpenRent don't
     * expose station lists, so this is undefined for those listings.
     */
    stationRoutes: jsonb("station_routes").$type<
      Array<{
        name: string;
        walkMinutes: number | null;
        transitMinutes: number | null;
      }>
    >(),
    aiRunId: text("ai_run_id").references(() => aiRuns.id, {
      onDelete: "set null",
      onUpdate: "cascade",
    }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    uniqueIndex("enrichments_listing_prompt_version_uniq").on(
      t.listingId,
      t.promptVersion
    ),
  ]
);

export const swipes = pgTable(
  "swipes",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade", onUpdate: "cascade" }),
    clusterId: text("cluster_id")
      .notNull()
      // Restrict — swipes record user decisions and must not be silently
      // dropped if a cluster row is ever removed.
      .references(() => propertyClusters.id, {
        onDelete: "restrict",
        onUpdate: "cascade",
      }),
    searchId: text("search_id")
      .notNull()
      .references(() => searches.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    outcome: swipeOutcomeEnum("outcome").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    uniqueIndex("swipes_user_cluster_search_uniq").on(
      t.userId,
      t.clusterId,
      t.searchId
    ),
    index("swipes_cluster_search_idx").on(t.clusterId, t.searchId),
    index("swipes_user_id_idx").on(t.userId),
  ]
);

/**
 * Pipeline state for clusters a household has mutually shortlisted.
 *
 * The "shortlisted" stage is derived from `v_mutual_matches` (every
 * member has kept-or-shortlisted the cluster); we ONLY write a row
 * here once the household moves the cluster forward (or archives it).
 * That keeps the table small and sidesteps the "backfill mutual
 * matches" question — the kanban's "Shortlisted" column always shows
 * the live derived list, augmented (subtracted) by any rows here that
 * have advanced to a later stage.
 *
 * Keyed on (household_id, cluster_id) — pipeline is a property of the
 * household, not of any one search. If the same cluster appears in two
 * searches the household is running, there's still one pipeline state.
 */
export const shortlistPipeline = pgTable(
  "shortlist_pipeline",
  {
    id: text("id").primaryKey(),
    householdId: text("household_id")
      .notNull()
      .references(() => households.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    clusterId: text("cluster_id")
      .notNull()
      // Restrict — household decisions are durable; we don't want a
      // cluster delete to silently wipe "we made an offer on this".
      .references(() => propertyClusters.id, {
        onDelete: "restrict",
        onUpdate: "cascade",
      }),
    status: pipelineStatusEnum("status").notNull(),
    /**
     * Why the row landed in `archived`. NULL for non-archived rows. The
     * enum is small + closed-set today; if more reasons emerge we add
     * via migration.
     */
    archivedReason: pipelineArchivedReasonEnum("archived_reason"),
    /**
     * Free-text notes visible to every household member. Optional —
     * deliberately not threaded; one shared scratchpad per card keeps
     * the v1 surface area small.
     */
    notes: text("notes"),
    /**
     * Audit columns — who last moved it and when. Drives the
     * "Moved 2 days ago by Alice" line on each kanban card so the
     * household can see who's pushing things forward.
     */
    lastMovedAt: timestamp("last_moved_at").defaultNow().notNull(),
    lastMovedByUserId: text("last_moved_by_user_id")
      .notNull()
      .references(() => user.id, {
        onDelete: "restrict",
        onUpdate: "cascade",
      }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (t) => [
    uniqueIndex("shortlist_pipeline_household_cluster_uniq").on(
      t.householdId,
      t.clusterId
    ),
    index("shortlist_pipeline_household_status_idx").on(
      t.householdId,
      t.status
    ),
  ]
);

/**
 * One row per household+cluster we've sent a "you both want this" match
 * email for. Presence = already notified; the unique index lets the swipe
 * path claim the notification atomically (INSERT … ON CONFLICT DO NOTHING)
 * so two members swiping near-simultaneously can't both fire the email.
 */
export const matchNotifications = pgTable(
  "match_notifications",
  {
    id: text("id").primaryKey(),
    householdId: text("household_id")
      .notNull()
      .references(() => households.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    clusterId: text("cluster_id")
      .notNull()
      .references(() => propertyClusters.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    notifiedAt: timestamp("notified_at").defaultNow().notNull(),
  },
  (t) => [
    uniqueIndex("match_notifications_household_cluster_uniq").on(
      t.householdId,
      t.clusterId
    ),
  ]
);

export const scrapeRuns = pgTable("scrape_runs", {
  id: text("id").primaryKey(),
  searchId: text("search_id")
    .notNull()
    .references(() => searches.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
  portal: text("portal").notNull(),
  startedAt: timestamp("started_at").defaultNow().notNull(),
  finishedAt: timestamp("finished_at"),
  status: jobStatusEnum("status").notNull(),
  listingsFound: integer("listings_found").default(0).notNull(),
  newListings: integer("new_listings").default(0).notNull(),
  errorMessage: text("error_message"),
  costUsd: numeric("cost_usd"),
  /**
   * R2 object key pointing at the gzipped raw HTML this run pulled
   * from Zyte (`{portal}/{scope}/{run_id}.html.gz`). Lets future
   * parser improvements backfill new fields from the archived bytes
   * instead of re-spending Zyte. `null` when R2 creds aren't staged
   * or the upload errored (the run still finalises — raw_key is
   * best-effort).
   */
  rawKey: text("raw_key"),
});

// Per-user UI state. Today's only field is `lastSeenMatches` — the
// timestamp the Matches tab badge clears against. Keyed on userId
// (1:1 with `user`) so we never have to think about which row to
// update. Cascades on user delete; Better Auth owns the `user` table
// (`better_auth` schema) but the FK works across schemas fine.
export const userState = pgTable("user_state", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade", onUpdate: "cascade" }),
  lastSeenMatches: timestamp("last_seen_matches").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .$onUpdate(() => new Date())
    .notNull(),
});

// -----------------------------------------------------------------------------
// Views
// -----------------------------------------------------------------------------

// v_mutual_matches — N-member count-based aggregate. A cluster appears in
// the mutual feed when EVERY active household member has kept-or-
// shortlisted it. Works for households of size 1 (solo auto-mutual), 2
// (couples), or any N. Replaces the old self-join shape which assumed
// exactly two users. See PLAN.md "Schema migration 0001_n_member_mutual_matches".
export const vMutualMatches = pgView("v_mutual_matches", {
  clusterId: text("cluster_id").notNull(),
  searchId: text("search_id").notNull(),
  householdId: text("household_id").notNull(),
  matchedAt: timestamp("matched_at").notNull(),
}).as(sql`
  SELECT a.cluster_id, a.search_id, a.household_id, a.matched_at
  FROM (
    SELECT
      sw.cluster_id,
      sw.search_id,
      s.household_id,
      COUNT(DISTINCT sw.user_id) AS agree_count,
      MAX(sw.created_at) AS matched_at
    FROM swipes sw
    JOIN searches s ON s.id = sw.search_id
    WHERE sw.outcome IN ('keep','shortlist')
    GROUP BY sw.cluster_id, sw.search_id, s.household_id
  ) a
  JOIN (
    SELECT household_id, COUNT(*) AS member_count
    FROM household_members
    GROUP BY household_id
  ) m ON m.household_id = a.household_id
  WHERE a.agree_count = m.member_count
`);

// -----------------------------------------------------------------------------
// Relations
// -----------------------------------------------------------------------------

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
  householdMemberships: many(householdMembers),
  swipes: many(swipes),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));

export const householdRelations = relations(households, ({ many }) => ({
  members: many(householdMembers),
  searches: many(searches),
}));

export const householdMembersRelations = relations(
  householdMembers,
  ({ one }) => ({
    household: one(households, {
      fields: [householdMembers.householdId],
      references: [households.id],
    }),
    user: one(user, {
      fields: [householdMembers.userId],
      references: [user.id],
    }),
  })
);

export const searchesRelations = relations(searches, ({ one, many }) => ({
  household: one(households, {
    fields: [searches.householdId],
    references: [households.id],
  }),
  listings: many(listings),
  swipes: many(swipes),
  scrapeRuns: many(scrapeRuns),
}));

export const propertyClustersRelations = relations(
  propertyClusters,
  ({ many }) => ({
    listings: many(listings),
    swipes: many(swipes),
  })
);

export const listingsRelations = relations(listings, ({ one, many }) => ({
  cluster: one(propertyClusters, {
    fields: [listings.clusterId],
    references: [propertyClusters.id],
  }),
  search: one(searches, {
    fields: [listings.searchId],
    references: [searches.id],
  }),
  photos: many(listingPhotos),
  enrichments: many(enrichments),
  aiRuns: many(aiRuns),
}));

export const listingPhotosRelations = relations(listingPhotos, ({ one }) => ({
  listing: one(listings, {
    fields: [listingPhotos.listingId],
    references: [listings.id],
  }),
}));

export const enrichmentsRelations = relations(enrichments, ({ one }) => ({
  listing: one(listings, {
    fields: [enrichments.listingId],
    references: [listings.id],
  }),
  aiRun: one(aiRuns, {
    fields: [enrichments.aiRunId],
    references: [aiRuns.id],
  }),
}));

export const swipesRelations = relations(swipes, ({ one }) => ({
  user: one(user, {
    fields: [swipes.userId],
    references: [user.id],
  }),
  cluster: one(propertyClusters, {
    fields: [swipes.clusterId],
    references: [propertyClusters.id],
  }),
  search: one(searches, {
    fields: [swipes.searchId],
    references: [searches.id],
  }),
}));

export const scrapeRunsRelations = relations(scrapeRuns, ({ one }) => ({
  search: one(searches, {
    fields: [scrapeRuns.searchId],
    references: [searches.id],
  }),
}));

export const aiRunsRelations = relations(aiRuns, ({ one, many }) => ({
  listing: one(listings, {
    fields: [aiRuns.listingId],
    references: [listings.id],
  }),
  enrichments: many(enrichments),
}));

export const shortlistPipelineRelations = relations(
  shortlistPipeline,
  ({ one }) => ({
    household: one(households, {
      fields: [shortlistPipeline.householdId],
      references: [households.id],
    }),
    cluster: one(propertyClusters, {
      fields: [shortlistPipeline.clusterId],
      references: [propertyClusters.id],
    }),
    lastMovedBy: one(user, {
      fields: [shortlistPipeline.lastMovedByUserId],
      references: [user.id],
    }),
  })
);

// -----------------------------------------------------------------------------
// Inferred types
// -----------------------------------------------------------------------------

export type User = typeof user.$inferSelect;
export type NewUser = typeof user.$inferInsert;

export type Session = typeof session.$inferSelect;
export type NewSession = typeof session.$inferInsert;

export type Account = typeof account.$inferSelect;
export type NewAccount = typeof account.$inferInsert;

export type Verification = typeof verification.$inferSelect;
export type NewVerification = typeof verification.$inferInsert;

export type Household = typeof households.$inferSelect;
export type NewHousehold = typeof households.$inferInsert;

export type HouseholdMember = typeof householdMembers.$inferSelect;
export type NewHouseholdMember = typeof householdMembers.$inferInsert;

export type Search = typeof searches.$inferSelect;
export type NewSearch = typeof searches.$inferInsert;

export type Listing = typeof listings.$inferSelect;
export type NewListing = typeof listings.$inferInsert;

export type PropertyCluster = typeof propertyClusters.$inferSelect;
export type NewPropertyCluster = typeof propertyClusters.$inferInsert;

export type ListingPhoto = typeof listingPhotos.$inferSelect;
export type NewListingPhoto = typeof listingPhotos.$inferInsert;

export type Enrichment = typeof enrichments.$inferSelect;
export type NewEnrichment = typeof enrichments.$inferInsert;

export type Swipe = typeof swipes.$inferSelect;
export type NewSwipe = typeof swipes.$inferInsert;

export type ScrapeRun = typeof scrapeRuns.$inferSelect;
export type NewScrapeRun = typeof scrapeRuns.$inferInsert;

export type AiRun = typeof aiRuns.$inferSelect;
export type NewAiRun = typeof aiRuns.$inferInsert;

export type UserState = typeof userState.$inferSelect;
export type NewUserState = typeof userState.$inferInsert;

export type ShortlistPipeline = typeof shortlistPipeline.$inferSelect;
export type NewShortlistPipeline = typeof shortlistPipeline.$inferInsert;

export type CouncilTaxRate = typeof councilTaxRates.$inferSelect;
export type NewCouncilTaxRate = typeof councilTaxRates.$inferInsert;

export type MatchNotification = typeof matchNotifications.$inferSelect;
export type NewMatchNotification = typeof matchNotifications.$inferInsert;
