/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchesIndexRouteImport } from './routes/searches/index'
import { Route as SettingsHouseholdRouteImport } from './routes/settings/household'
import { Route as SearchesNewRouteImport } from './routes/searches/new'
import { Route as SearchesIdRouteImport } from './routes/searches/$id'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchesIndexRoute = SearchesIndexRouteImport.update({
  id: '/searches/',
  path: '/searches/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHouseholdRoute = SettingsHouseholdRouteImport.update({
  id: '/settings/household',
  path: '/settings/household',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchesNewRoute = SearchesNewRouteImport.update({
  id: '/searches/new',
  path: '/searches/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchesIdRoute = SearchesIdRouteImport.update({
  id: '/searches/$id',
  path: '/searches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invite/$token': typeof InviteTokenRoute
  '/searches/$id': typeof SearchesIdRoute
  '/searches/new': typeof SearchesNewRoute
  '/settings/household': typeof SettingsHouseholdRoute
  '/searches/': typeof SearchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite/$token': typeof InviteTokenRoute
  '/searches/$id': typeof SearchesIdRoute
  '/searches/new': typeof SearchesNewRoute
  '/settings/household': typeof SettingsHouseholdRoute
  '/searches': typeof SearchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invite/$token': typeof InviteTokenRoute
  '/searches/$id': typeof SearchesIdRoute
  '/searches/new': typeof SearchesNewRoute
  '/settings/household': typeof SettingsHouseholdRoute
  '/searches/': typeof SearchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invite/$token'
    | '/searches/$id'
    | '/searches/new'
    | '/settings/household'
    | '/searches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite/$token'
    | '/searches/$id'
    | '/searches/new'
    | '/settings/household'
    | '/searches'
  id:
    | '__root__'
    | '/'
    | '/invite/$token'
    | '/searches/$id'
    | '/searches/new'
    | '/settings/household'
    | '/searches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InviteTokenRoute: typeof InviteTokenRoute
  SearchesIdRoute: typeof SearchesIdRoute
  SearchesNewRoute: typeof SearchesNewRoute
  SettingsHouseholdRoute: typeof SettingsHouseholdRoute
  SearchesIndexRoute: typeof SearchesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/searches/': {
      id: '/searches/'
      path: '/searches'
      fullPath: '/searches/'
      preLoaderRoute: typeof SearchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/household': {
      id: '/settings/household'
      path: '/settings/household'
      fullPath: '/settings/household'
      preLoaderRoute: typeof SettingsHouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/searches/new': {
      id: '/searches/new'
      path: '/searches/new'
      fullPath: '/searches/new'
      preLoaderRoute: typeof SearchesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/searches/$id': {
      id: '/searches/$id'
      path: '/searches/$id'
      fullPath: '/searches/$id'
      preLoaderRoute: typeof SearchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InviteTokenRoute: InviteTokenRoute,
  SearchesIdRoute: SearchesIdRoute,
  SearchesNewRoute: SearchesNewRoute,
  SettingsHouseholdRoute: SettingsHouseholdRoute,
  SearchesIndexRoute: SearchesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
