/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShortlistRouteImport } from './routes/shortlist'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchesIndexRouteImport } from './routes/searches/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SettingsHouseholdRouteImport } from './routes/settings/household'
import { Route as SearchesNewRouteImport } from './routes/searches/new'
import { Route as SearchesIdRouteImport } from './routes/searches/$id'
import { Route as ListingsClusterIdRouteImport } from './routes/listings/$clusterId'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AdminSpendRouteImport } from './routes/admin/spend'
import { Route as AdminSchedulesRouteImport } from './routes/admin/schedules'
import { Route as AdminRunsRouteImport } from './routes/admin/runs'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortlistRoute = ShortlistRouteImport.update({
  id: '/shortlist',
  path: '/shortlist',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchesIndexRoute = SearchesIndexRouteImport.update({
  id: '/searches/',
  path: '/searches/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHouseholdRoute = SettingsHouseholdRouteImport.update({
  id: '/settings/household',
  path: '/settings/household',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchesNewRoute = SearchesNewRouteImport.update({
  id: '/searches/new',
  path: '/searches/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchesIdRoute = SearchesIdRouteImport.update({
  id: '/searches/$id',
  path: '/searches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsClusterIdRoute = ListingsClusterIdRouteImport.update({
  id: '/listings/$clusterId',
  path: '/listings/$clusterId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSpendRoute = AdminSpendRouteImport.update({
  id: '/admin/spend',
  path: '/admin/spend',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSchedulesRoute = AdminSchedulesRouteImport.update({
  id: '/admin/schedules',
  path: '/admin/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRunsRoute = AdminRunsRouteImport.update({
  id: '/admin/runs',
  path: '/admin/runs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/shortlist': typeof ShortlistRoute
  '/signup': typeof SignupRoute
  '/admin/runs': typeof AdminRunsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/spend': typeof AdminSpendRoute
  '/invite/$token': typeof InviteTokenRoute
  '/listings/$clusterId': typeof ListingsClusterIdRoute
  '/searches/$id': typeof SearchesIdRoute
  '/searches/new': typeof SearchesNewRoute
  '/settings/household': typeof SettingsHouseholdRoute
  '/admin/': typeof AdminIndexRoute
  '/searches/': typeof SearchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/shortlist': typeof ShortlistRoute
  '/signup': typeof SignupRoute
  '/admin/runs': typeof AdminRunsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/spend': typeof AdminSpendRoute
  '/invite/$token': typeof InviteTokenRoute
  '/listings/$clusterId': typeof ListingsClusterIdRoute
  '/searches/$id': typeof SearchesIdRoute
  '/searches/new': typeof SearchesNewRoute
  '/settings/household': typeof SettingsHouseholdRoute
  '/admin': typeof AdminIndexRoute
  '/searches': typeof SearchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/shortlist': typeof ShortlistRoute
  '/signup': typeof SignupRoute
  '/admin/runs': typeof AdminRunsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/spend': typeof AdminSpendRoute
  '/invite/$token': typeof InviteTokenRoute
  '/listings/$clusterId': typeof ListingsClusterIdRoute
  '/searches/$id': typeof SearchesIdRoute
  '/searches/new': typeof SearchesNewRoute
  '/settings/household': typeof SettingsHouseholdRoute
  '/admin/': typeof AdminIndexRoute
  '/searches/': typeof SearchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/matches'
    | '/shortlist'
    | '/signup'
    | '/admin/runs'
    | '/admin/schedules'
    | '/admin/spend'
    | '/invite/$token'
    | '/listings/$clusterId'
    | '/searches/$id'
    | '/searches/new'
    | '/settings/household'
    | '/admin/'
    | '/searches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/matches'
    | '/shortlist'
    | '/signup'
    | '/admin/runs'
    | '/admin/schedules'
    | '/admin/spend'
    | '/invite/$token'
    | '/listings/$clusterId'
    | '/searches/$id'
    | '/searches/new'
    | '/settings/household'
    | '/admin'
    | '/searches'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/matches'
    | '/shortlist'
    | '/signup'
    | '/admin/runs'
    | '/admin/schedules'
    | '/admin/spend'
    | '/invite/$token'
    | '/listings/$clusterId'
    | '/searches/$id'
    | '/searches/new'
    | '/settings/household'
    | '/admin/'
    | '/searches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  ShortlistRoute: typeof ShortlistRoute
  SignupRoute: typeof SignupRoute
  AdminRunsRoute: typeof AdminRunsRoute
  AdminSchedulesRoute: typeof AdminSchedulesRoute
  AdminSpendRoute: typeof AdminSpendRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ListingsClusterIdRoute: typeof ListingsClusterIdRoute
  SearchesIdRoute: typeof SearchesIdRoute
  SearchesNewRoute: typeof SearchesNewRoute
  SettingsHouseholdRoute: typeof SettingsHouseholdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  SearchesIndexRoute: typeof SearchesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortlist': {
      id: '/shortlist'
      path: '/shortlist'
      fullPath: '/shortlist'
      preLoaderRoute: typeof ShortlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/searches/': {
      id: '/searches/'
      path: '/searches'
      fullPath: '/searches/'
      preLoaderRoute: typeof SearchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/household': {
      id: '/settings/household'
      path: '/settings/household'
      fullPath: '/settings/household'
      preLoaderRoute: typeof SettingsHouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/searches/new': {
      id: '/searches/new'
      path: '/searches/new'
      fullPath: '/searches/new'
      preLoaderRoute: typeof SearchesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/searches/$id': {
      id: '/searches/$id'
      path: '/searches/$id'
      fullPath: '/searches/$id'
      preLoaderRoute: typeof SearchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$clusterId': {
      id: '/listings/$clusterId'
      path: '/listings/$clusterId'
      fullPath: '/listings/$clusterId'
      preLoaderRoute: typeof ListingsClusterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/spend': {
      id: '/admin/spend'
      path: '/admin/spend'
      fullPath: '/admin/spend'
      preLoaderRoute: typeof AdminSpendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/schedules': {
      id: '/admin/schedules'
      path: '/admin/schedules'
      fullPath: '/admin/schedules'
      preLoaderRoute: typeof AdminSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/runs': {
      id: '/admin/runs'
      path: '/admin/runs'
      fullPath: '/admin/runs'
      preLoaderRoute: typeof AdminRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  ShortlistRoute: ShortlistRoute,
  SignupRoute: SignupRoute,
  AdminRunsRoute: AdminRunsRoute,
  AdminSchedulesRoute: AdminSchedulesRoute,
  AdminSpendRoute: AdminSpendRoute,
  InviteTokenRoute: InviteTokenRoute,
  ListingsClusterIdRoute: ListingsClusterIdRoute,
  SearchesIdRoute: SearchesIdRoute,
  SearchesNewRoute: SearchesNewRoute,
  SettingsHouseholdRoute: SettingsHouseholdRoute,
  AdminIndexRoute: AdminIndexRoute,
  SearchesIndexRoute: SearchesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
